### ISSUE TITLE
cannot clone recursively (and as a result cannot run the very first cargo make command)

### ISSUE THREAD

**Issue by zecoxao** [TeumessianFox/ASPFuzz#1]
due to the wonderful job of github (perhaps they are collecting Easter Eggs right now), i cannot for the life of me recursively clone the repo (or submodule initialize for that matter) which results in the inhability to run the first cargo make test command due to how qemu repo handles this.

if anyone has a solution for this, please let me know. thank you and appreciate it

**Comment by TeumessianFox** [comment]
Hi @zecoxao, could you please provide some more details of your issue? Which step is failing and what error message are you getting?

**Comment by zecoxao** [comment]
sure @TeumessianFox , here is the log
zecoxao@DESKTOP-AP6P41T:/mnt/c/Users/zecoxao/Desktop/test_folder$ git clone --recursive https://github.com/TeumessianFox/ASPFuzz
Cloning into 'ASPFuzz'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 43 (delta 6), reused 43 (delta 6), pack-reused 0
Receiving objects: 100% (43/43), 1.29 MiB | 5.34 MiB/s, done.
Resolving deltas: 100% (6/6), done.
Updating files: 100% (33/33), done.
Submodule 'LibAFL' (git@github.com:TeumessianFox/LibAFL.git) registered for path 'LibAFL'
Submodule 'qemu-libafl-asp' (git@github.com:TeumessianFox/qemu-libafl-asp.git) registered for path 'qemu-libafl-asp'
Cloning into '/mnt/c/Users/zecoxao/Desktop/test_folder/ASPFuzz/LibAFL'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:TeumessianFox/LibAFL.git' into submodule path '/mnt/c/Users/zecoxao/Desktop/test_folder/ASPFuzz/LibAFL' failed
Failed to clone 'LibAFL'. Retry scheduled
Cloning into '/mnt/c/Users/zecoxao/Desktop/test_folder/ASPFuzz/qemu-libafl-asp'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:TeumessianFox/qemu-libafl-asp.git' into submodule path '/mnt/c/Users/zecoxao/Desktop/test_folder/ASPFuzz/qemu-libafl-asp' failed
Failed to clone 'qemu-libafl-asp'. Retry scheduled
Cloning into '/mnt/c/Users/zecoxao/Desktop/test_folder/ASPFuzz/LibAFL'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:TeumessianFox/LibAFL.git' into submodule path '/mnt/c/Users/zecoxao/Desktop/test_folder/ASPFuzz/LibAFL' failed
Failed to clone 'LibAFL' a second time, aborting

**Comment by zecoxao** [comment]
if i do 
git submodule update --init
i get the exact same errors as above

**Comment by TeumessianFox** [comment]
I will have a look at that tomorrow. Can you clone TeumessianFox/LibAFL.git and TeumessianFox/qemu-libafl-asp.git by itself?

**Comment by zecoxao** [comment]
i can, yes. but after attempting to compile the yaml, that leads to more errors.

the first error is that a certain header is missing on a folder called libafl_extras

--- stderr
  make: *** [Makefile:165: run-ninja] Erro 1
  /home/zecoxao/Desktop/ASPFuzz/fuzzer/amd_sp/../../qemu-libafl-asp/build/wrapper.h:44:10: fatal error: 'libafl_extras/syx-snapshot/syx-snapshot.h' file not found
  
  this is "fixed" (i presume) by adding the folder libafl_extras from this repository
  
  https://github.com/AFLplusplus/qemu-libafl-bridge
  
  to the qemu recursively cloned folder.
  
  after that it errors further with the following two errors:
  
  error[E0599]: no method named cpu_reset found for struct CPU in the current scope
   --> /home/zecoxao/Desktop/ASPFuzz/fuzzer/libasp/src/reset_state.rs:213:13
    |
213 |         cpu.cpu_reset();
    |             ^^^^^^^^^ help: there is a method with a similar name: reset

error[E0599]: no method named start found for reference &libafl_qemu::Emulator in the current scope
   --> /home/zecoxao/Desktop/ASPFuzz/fuzzer/libasp/src/reset_state.rs:240:13
    |
240 |         emu.start(&cpu);
    |             ^^^^^ method not found in &libafl_qemu::Emulator

For more information about this error, try rustc --explain E0599.
error: could not compile libasp due to 2 previous errors

and at this point i'm clueless as to what to do

**Comment by TeumessianFox** [comment]
I updated the repo. It might have been an issue on my side with the submodules. Please try again, it should look like this:

```
➜  test git clone https://github.com/TeumessianFox/ASPFuzz.git
Cloning into 'ASPFuzz'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 46 (delta 8), reused 46 (delta 8), pack-reused 0
Unpacking objects: 100% (46/46), 1.29 MiB | 3.57 MiB/s, done.
➜  test cd ASPFuzz 
➜  ASPFuzz git:(master) git submodule update --init                           
Submodule 'LibAFL' (https://github.com/TeumessianFox/LibAFL.git) registered for path 'LibAFL'
Submodule 'qemu-libafl-asp' (https://github.com/TeumessianFox/qemu-libafl-asp.git) registered for path 'qemu-libafl-asp'
Cloning into '/test/ASPFuzz/LibAFL'...
Cloning into '/test/ASPFuzz/qemu-libafl-asp'...
Submodule path 'LibAFL': checked out 'eb52fb7c03f7c47d273a9e8d45c4e4f6c3ef03a1'
Submodule path 'qemu-libafl-asp': checked out '9b3b891c3e7a7f2a733af55ed95c7f8daae95180'
```

**Comment by zecoxao** [comment]
the recursive clone problem seems to be solved. as for the other issues, i'll compile and let you know if they show up. thanks
